// Code generated by eos-bindgen (stub). DO NOT EDIT.
// TODO: Replace with auto-generated bindings from EOS SDK headers.

package cbinding

type EOS_LogMessage struct {
	Category string
	Level    EOS_ELogLevel
	Message  string
}

type EOS_LogMessageFunc func(msg *EOS_LogMessage)

var logCallback EOS_LogMessageFunc

func EOS_Logging_SetCallback(fn EOS_LogMessageFunc) EOS_EResult {
	logCallback = fn
	return EOS_EResult_Success
}

func EOS_Logging_SetLogLevel(category EOS_ELogCategory, level EOS_ELogLevel) EOS_EResult {
	return EOS_EResult_Success
}

// SimulateLogMessage is a test helper that fires the registered log callback.
// This function only exists in the stub and will be removed with real bindings.
func SimulateLogMessage(msg *EOS_LogMessage) {
	if logCallback != nil {
		logCallback(msg)
	}
}
