// Code generated by eos-bindgen (stub). DO NOT EDIT.
// TODO: Replace with auto-generated bindings from EOS SDK headers.

package cbinding

type EOS_InitializeOptions struct {
	ProductName    string
	ProductVersion string
}

type EOS_Platform_Options struct {
	ProductId    string
	SandboxId    string
	DeploymentId string
	ClientId     string
	ClientSecret string
}

func EOS_Initialize(opts *EOS_InitializeOptions) EOS_EResult {
	return EOS_EResult_Success
}

func EOS_Platform_Create(opts *EOS_Platform_Options) EOS_HPlatform {
	return EOS_HPlatform(1)
}

func EOS_Platform_Tick(handle EOS_HPlatform) {}

func EOS_Platform_Release(handle EOS_HPlatform) {}

func EOS_Shutdown() EOS_EResult {
	return EOS_EResult_Success
}

func EOS_Platform_GetAuthInterface(handle EOS_HPlatform) EOS_HAuth {
	return EOS_HAuth(1)
}

func EOS_Platform_GetConnectInterface(handle EOS_HPlatform) EOS_HConnect {
	return EOS_HConnect(1)
}

func EOS_Platform_GetLobbyInterface(handle EOS_HPlatform) EOS_HLobby {
	return EOS_HLobby(1)
}

func EOS_Platform_GetSessionsInterface(handle EOS_HPlatform) EOS_HSessions {
	return EOS_HSessions(1)
}

func EOS_Platform_GetP2PInterface(handle EOS_HPlatform) EOS_HP2P {
	return EOS_HP2P(1)
}
