// Code generated by eos-bindgen (stub). DO NOT EDIT.
// TODO: Replace with auto-generated bindings from EOS SDK headers.

package cbinding

type EOS_HPlatform uintptr
type EOS_HAuth uintptr
type EOS_HConnect uintptr
type EOS_HLobby uintptr
type EOS_HSessions uintptr
type EOS_HP2P uintptr

type EOS_EResult int32

const (
	EOS_EResult_Success         EOS_EResult = 0
	EOS_EResult_NoConnection    EOS_EResult = 1
	EOS_EResult_InvalidAuth     EOS_EResult = 4
	EOS_EResult_TooManyRequests EOS_EResult = 8
	EOS_EResult_AlreadyPending  EOS_EResult = 9
	EOS_EResult_NotFound        EOS_EResult = 18
	EOS_EResult_UnexpectedError EOS_EResult = 0x7FFFFFFF
)

type EOS_EpicAccountId uintptr
type EOS_ProductUserId uintptr
type EOS_NotificationId uint64

type EOS_Bool int32

const (
	EOS_TRUE  EOS_Bool = 1
	EOS_FALSE EOS_Bool = 0
)

type EOS_ELogCategory int32

const (
	EOS_LC_Core          EOS_ELogCategory = 0
	EOS_LC_Auth          EOS_ELogCategory = 1
	EOS_LC_Friends       EOS_ELogCategory = 2
	EOS_LC_Presence      EOS_ELogCategory = 3
	EOS_LC_AllCategories EOS_ELogCategory = 0x7FFFFFFF
)

type EOS_ContinuanceToken uintptr

type EOS_ELoginCredentialType int32
type EOS_EAuthScopeFlags uint64
type EOS_EExternalCredentialType int32

type EOS_ELoginStatus int32

const (
	EOS_LS_NotLoggedIn       EOS_ELoginStatus = 0
	EOS_LS_UsingLocalProfile EOS_ELoginStatus = 1
	EOS_LS_LoggedIn          EOS_ELoginStatus = 2
)

type EOS_ELogLevel int32

const (
	EOS_LOG_Off         EOS_ELogLevel = 0
	EOS_LOG_Fatal       EOS_ELogLevel = 100
	EOS_LOG_Error       EOS_ELogLevel = 200
	EOS_LOG_Warning     EOS_ELogLevel = 300
	EOS_LOG_Info        EOS_ELogLevel = 400
	EOS_LOG_Verbose     EOS_ELogLevel = 500
	EOS_LOG_VeryVerbose EOS_ELogLevel = 600
)
