// Code generated by eos-bindgen (stub). DO NOT EDIT.
// TODO: Replace with auto-generated bindings from EOS SDK headers.

package cbinding

type EOS_HPlatform uintptr
type EOS_HAuth uintptr
type EOS_HConnect uintptr
type EOS_HLobby uintptr
type EOS_HSessions uintptr
type EOS_HP2P uintptr

type EOS_EResult int32

const (
	EOS_EResult_Success             EOS_EResult = 0
	EOS_EResult_NoConnection        EOS_EResult = 1
	EOS_EResult_InvalidAuth         EOS_EResult = 4
	EOS_EResult_TooManyRequests     EOS_EResult = 8
	EOS_EResult_AlreadyPending      EOS_EResult = 9
	EOS_EResult_NotFound            EOS_EResult = 18
	EOS_EResult_DuplicateNotAllowed EOS_EResult = 24
	EOS_EResult_UnexpectedError     EOS_EResult = 0x7FFFFFFF
)

type EOS_EpicAccountId uintptr
type EOS_ProductUserId uintptr
type EOS_NotificationId uint64

type EOS_Bool int32

const (
	EOS_TRUE  EOS_Bool = 1
	EOS_FALSE EOS_Bool = 0
)

type EOS_ELogCategory int32

const (
	EOS_LC_Core          EOS_ELogCategory = 0
	EOS_LC_Auth          EOS_ELogCategory = 1
	EOS_LC_Friends       EOS_ELogCategory = 2
	EOS_LC_Presence      EOS_ELogCategory = 3
	EOS_LC_AllCategories EOS_ELogCategory = 0x7FFFFFFF
)

type EOS_ContinuanceToken uintptr

type EOS_ELoginCredentialType int32
type EOS_EAuthScopeFlags uint64
type EOS_EExternalCredentialType int32

type EOS_ELoginStatus int32

const (
	EOS_LS_NotLoggedIn       EOS_ELoginStatus = 0
	EOS_LS_UsingLocalProfile EOS_ELoginStatus = 1
	EOS_LS_LoggedIn          EOS_ELoginStatus = 2
)

// Lobby/Sessions handle types

type EOS_HLobbyModification uintptr
type EOS_HLobbySearch uintptr
type EOS_HLobbyDetails uintptr
type EOS_HSessionModification uintptr
type EOS_HSessionSearch uintptr
type EOS_HSessionDetails uintptr
type EOS_HActiveSession uintptr

// Lobby enums

type EOS_ELobbyPermissionLevel int32

const (
	EOS_LPL_PublicAdvertised EOS_ELobbyPermissionLevel = 0
	EOS_LPL_JoinViaPresence  EOS_ELobbyPermissionLevel = 1
	EOS_LPL_InviteOnly       EOS_ELobbyPermissionLevel = 2
)

type EOS_ELobbyAttributeVisibility int32

const (
	EOS_LAT_Public  EOS_ELobbyAttributeVisibility = 0
	EOS_LAT_Private EOS_ELobbyAttributeVisibility = 1
)

type EOS_ELobbyMemberStatus int32

const (
	EOS_LMS_Joined       EOS_ELobbyMemberStatus = 0
	EOS_LMS_Left         EOS_ELobbyMemberStatus = 1
	EOS_LMS_Disconnected EOS_ELobbyMemberStatus = 2
	EOS_LMS_Kicked       EOS_ELobbyMemberStatus = 3
	EOS_LMS_Promoted     EOS_ELobbyMemberStatus = 4
	EOS_LMS_Closed       EOS_ELobbyMemberStatus = 5
)

// Sessions enums

type EOS_EOnlineSessionState int32

const (
	EOS_OSS_NoSession  EOS_EOnlineSessionState = 0
	EOS_OSS_Creating   EOS_EOnlineSessionState = 1
	EOS_OSS_Pending    EOS_EOnlineSessionState = 2
	EOS_OSS_Starting   EOS_EOnlineSessionState = 3
	EOS_OSS_InProgress EOS_EOnlineSessionState = 4
	EOS_OSS_Ending     EOS_EOnlineSessionState = 5
	EOS_OSS_Ended      EOS_EOnlineSessionState = 6
	EOS_OSS_Destroying EOS_EOnlineSessionState = 7
)

type EOS_EOnlineSessionPermissionLevel int32

const (
	EOS_OSPF_PublicAdvertised EOS_EOnlineSessionPermissionLevel = 0
	EOS_OSPF_JoinViaPresence  EOS_EOnlineSessionPermissionLevel = 1
	EOS_OSPF_InviteOnly       EOS_EOnlineSessionPermissionLevel = 2
)

type EOS_ESessionAttributeAdvertisementType int32

const (
	EOS_SAAT_DontAdvertise EOS_ESessionAttributeAdvertisementType = 0
	EOS_SAAT_Advertise     EOS_ESessionAttributeAdvertisementType = 1
)

// Shared enums (used by both lobby and sessions)

type EOS_EComparisonOp int32

const (
	EOS_CO_Equal              EOS_EComparisonOp = 0
	EOS_CO_NotEqual           EOS_EComparisonOp = 1
	EOS_CO_GreaterThan        EOS_EComparisonOp = 2
	EOS_CO_GreaterThanOrEqual EOS_EComparisonOp = 3
	EOS_CO_LessThan           EOS_EComparisonOp = 4
	EOS_CO_LessThanOrEqual    EOS_EComparisonOp = 5
	EOS_CO_Distance           EOS_EComparisonOp = 6
	EOS_CO_AnyOf              EOS_EComparisonOp = 7
	EOS_CO_NotAnyOf           EOS_EComparisonOp = 8
	EOS_CO_OneOf              EOS_EComparisonOp = 9
	EOS_CO_NotOneOf           EOS_EComparisonOp = 10
	EOS_CO_Contains           EOS_EComparisonOp = 11
)

type EOS_EAttributeType int32

const (
	EOS_AT_Boolean EOS_EAttributeType = 0
	EOS_AT_Int64   EOS_EAttributeType = 1
	EOS_AT_Double  EOS_EAttributeType = 2
	EOS_AT_String  EOS_EAttributeType = 3
)

type EOS_ELogLevel int32

const (
	EOS_LOG_Off         EOS_ELogLevel = 0
	EOS_LOG_Fatal       EOS_ELogLevel = 100
	EOS_LOG_Error       EOS_ELogLevel = 200
	EOS_LOG_Warning     EOS_ELogLevel = 300
	EOS_LOG_Info        EOS_ELogLevel = 400
	EOS_LOG_Verbose     EOS_ELogLevel = 500
	EOS_LOG_VeryVerbose EOS_ELogLevel = 600
)
